#Turn DatapackLoader off.
disable-plugin: false


#############################
#Datapack Downloader Options#
#############################

#Imports datapacks from .zip URLs. Examples given may not be up-to-date.
datapack-urls:
#  - 'https://www.stardustlabs.net/s/Terralith_119x_v235.zip'
#  - 'https://download2297.mediafire.com/6oydubv7s3eg/5xhz1b3hvq0ds3r/BlazeandCave%5C%27s+Advancements+Pack+1.15.2.zip'
#  - ...


#############################
#Datapack Developer Options##
#############################

#A starter datapack will generate inside the 'Datapacks' folder if 'Datapacks' is empty.
starter-datapack: false
#Uses misode's 'mcmeta' repository: https://github.com/misode/mcmeta

#The server will start up with new worlds loaded with the datapacks in 'Datapacks'.
#Combine this with a script provided in 'README.txt' for speed!
developer-mode: false
#WARNING: This deletes worlds!