#Turn DatapackLoader off.
disable-plugin: false


#############################
#Datapack Downloader Options#
#############################

#Imports datapacks from .zip URLs. Example given may not be up-to-date.
#Make sure the URL is not uniquely generated, like this one:
  #https://download2297.mediafire.com/6oydubv7s3eg/5xhz1b3hvq0ds3r/BlazeandCave%5C%27s+Advancements+Pack+1.15.2.zip
datapack-urls:
#  - 'https://www.stardustlabs.net/s/Terralith_119x_v235.zip'
#  - ...


#############################
#Datapack Developer Options##
#############################

#A starter datapack will generate inside the 'Datapacks' folder if 'Datapacks' is empty.
starter-datapack: false
#Uses misode's 'mcmeta' repository: https://github.com/misode/mcmeta

#The server will start up with new worlds loaded with the datapacks in 'Datapacks'.
#Combine this with PaperMC and a script provided in 'README.txt' for speed!
developer-mode: false
#WARNING: This is done by changing 'level-name' in 'server.properties' on server startup.
  #It will make the server restart a second time and delete worlds. It also generates an error on the first restart.
  #Do not use this feature on a production server!