name: DatapackLoader
version: "${project.version}"
main: com.lichenaut.datapackloader.Main
api-version: "1.20"
authors: [lichenaut]
description: Automatically add datapacks to your server.
load: STARTUP
commands:
  dl:
    description: "Base command for 'help' and 'import' commands."
  dltp:
    description: "Teleport to the center of any world in spectator mode."
