name: DatapackLoader
version: '1.02'
main: com.lichenaut.datapackloader.DatapackLoader
api-version: 1.19
authors: [ lichenaut ]
description: Automatically loads a datapack from the plugin folder into the server's main world, and more.
load: STARTUP
commands:
  dl:
    description: "Base argument for 'help' and 'import' commands."
  dltp:
    description: "Teleport to the center of any world in spectator mode."